/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package codigoFonte.view;

import codigoFonte.Controller.ConectarBD;
import codigoFonte.Controller.RoundedCornerBorder;
import codigoFonte.Controller.SetaPermissoes;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Eduardo Garcia( Mayhem-eng )
 */
public class telaDeCadastro extends javax.swing.JInternalFrame {

      ConectarBD conn = new ConectarBD();
    SetaPermissoes st = new SetaPermissoes();
    
    public telaDeCadastro() {
        initComponents();
        conn.statusConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField() {
            @Override protected void paintComponent(Graphics g) {
                if (!isOpaque() && getBorder() instanceof RoundedCornerBorder) {
                    Graphics2D g2 = (Graphics2D) g.create();
                    g2.setPaint(getBackground());
                    g2.fill(((RoundedCornerBorder) getBorder()).getBorderShape(
                        0, 0, getWidth() - 1, getHeight() - 1));
                g2.dispose();
            }
            super.paintComponent(g);
        }
        @Override public void updateUI() {
            super.updateUI();
            setOpaque(false);
            setBorder(new RoundedCornerBorder());
        }
    }
    ;
    txtEmail = new javax.swing.JTextField() {
        @Override protected void paintComponent(Graphics g) {
            if (!isOpaque() && getBorder() instanceof RoundedCornerBorder) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setPaint(getBackground());
                g2.fill(((RoundedCornerBorder) getBorder()).getBorderShape(
                    0, 0, getWidth() - 1, getHeight() - 1));
            g2.dispose();
        }
        super.paintComponent(g);
    }
    @Override public void updateUI() {
        super.updateUI();
        setOpaque(false);
        setBorder(new RoundedCornerBorder());
    }
    }
    ;
    txtTelefone = new javax.swing.JTextField() {
        @Override protected void paintComponent(Graphics g) {
            if (!isOpaque() && getBorder() instanceof RoundedCornerBorder) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setPaint(getBackground());
                g2.fill(((RoundedCornerBorder) getBorder()).getBorderShape(
                    0, 0, getWidth() - 1, getHeight() - 1));
            g2.dispose();
        }
        super.paintComponent(g);
    }
    @Override public void updateUI() {
        super.updateUI();
        setOpaque(false);
        setBorder(new RoundedCornerBorder());
    }
    }
    ;
    txtPassword = new javax.swing.JPasswordField(){
        @Override protected void paintComponent(Graphics g) {
            if (!isOpaque() && getBorder() instanceof RoundedCornerBorder) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setPaint(getBackground());
                g2.fill(((RoundedCornerBorder) getBorder()).getBorderShape(
                    0, 0, getWidth() - 1, getHeight() - 1));
            g2.dispose();
        }
        super.paintComponent(g);
    }
    @Override public void updateUI() {
        super.updateUI();
        setOpaque(false);
        setBorder(new RoundedCornerBorder());
    }
    }
    ;
    checkVerSenha = new javax.swing.JCheckBox();
    buttCadastrar = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setTitle("cadastro");

    jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
    jLabel2.setText("Cadastro");

    txtUsuario.setFont(new java.awt.Font("Perpetua Titling MT", 2, 18)); // NOI18N
    txtUsuario.setText("usuario");
    txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            txtUsuarioFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtUsuarioFocusLost(evt);
        }
    });

    txtEmail.setFont(new java.awt.Font("Perpetua Titling MT", 2, 18)); // NOI18N
    txtEmail.setText("email");
    txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            txtEmailFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtEmailFocusLost(evt);
        }
    });
    txtEmail.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtEmailActionPerformed(evt);
        }
    });

    txtTelefone.setFont(new java.awt.Font("Perpetua Titling MT", 2, 18)); // NOI18N
    txtTelefone.setText("telefone");
    txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            txtTelefoneFocusGained(evt);
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            txtTelefoneFocusLost(evt);
        }
    });

    txtPassword.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtPasswordActionPerformed(evt);
        }
    });

    checkVerSenha.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            checkVerSenhaItemStateChanged(evt);
        }
    });
    checkVerSenha.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            checkVerSenhaActionPerformed(evt);
        }
    });

    buttCadastrar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
    buttCadastrar.setText("Cadastrar-se");
    buttCadastrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttCadastrarActionPerformed(evt);
        }
    });

    jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 2, 12)); // NOI18N
    jLabel1.setText("senha:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkVerSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createSequentialGroup()
                    .addGap(193, 193, 193)
                    .addComponent(buttCadastrar))
                .addGroup(layout.createSequentialGroup()
                    .addGap(194, 194, 194)
                    .addComponent(jLabel2)))
            .addContainerGap(147, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(43, 43, 43)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(54, 54, 54)
            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(58, 58, 58)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(checkVerSenha)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addGap(29, 29, 29)))
            .addGap(55, 55, 55)
            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(101, 101, 101)
            .addComponent(buttCadastrar)
            .addContainerGap(144, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        txtUsuario.setText("");
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if(txtUsuario.getText().equals("")){
            txtUsuario.setText("usuário");
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(txtEmail.getText().equals("")){
            txtEmail.setText("email");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusGained
        txtTelefone.setText("");
    }//GEN-LAST:event_txtTelefoneFocusGained

    private void txtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusLost
        if(txtTelefone.getText().equals("")){
            txtTelefone.setText("telefone");
        }
    }//GEN-LAST:event_txtTelefoneFocusLost

    private void checkVerSenhaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkVerSenhaItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            txtPassword.setEchoChar((char)0);
        }
        else{
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_checkVerSenhaItemStateChanged

    private void checkVerSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkVerSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkVerSenhaActionPerformed

    private void buttCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttCadastrarActionPerformed
        String usuario = txtUsuario.getText();
        String senha = new String(txtPassword.getPassword());
        String telefone = txtTelefone.getText();
        String email = txtEmail.getText();

        if(!"".equals(usuario) && !"".equals(senha)){
            String sql = "insert into cadastro (usuario, senha, telefone, email) VALUES (?, ?, ?, ?);";
            try{
                conn.ptsm = conn.conexao.prepareStatement(sql);
                conn.ptsm.setString(1, usuario);
                conn.ptsm.setString(2, senha);
                conn.ptsm.setString(3, telefone);
                conn.ptsm.setString(4, email);
                conn.ptsm.executeUpdate();
                st.configurarPermissoes(usuario, senha, true, conn.ptsm);

            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Erro: "+ e.getMessage(), "Mensagem do programa", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttCadastrarActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttCadastrar;
    private javax.swing.JCheckBox checkVerSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
